services:
  app:
    image: blog-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blog-front

  server:
    image: blog-back
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog-back

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server