services:
  app:
    image: blog-front-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    container_name: blog-front-dev
    environment:
      - DANGEROUSLY_DISABLE_HOST_CHECK=true

  server:
    image: blog-back-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3003:3003
    container_name: blog-back-dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server